name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag daelinc/minecraft-papermc:latest --tag daelinc/minecraft-papermc:$(date +%Y%m%d%H%M%S)

    - name: Push the Docker image to Docker Hub
      run: |
        docker push daelinc/minecraft-papermc:latest
        docker push daelinc/minecraft-papermc:$(date +%Y%m%d%H%M%S)
