name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        type: string
        required: false

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag daelinc/minecraft-papermc:${{ inputs.tag }} --tag daelinc/minecraft-papermc:latest

    - name: Push the Docker image to Docker Hub
      run: |
        docker push daelinc/minecraft-papermc:${{ inputs.tag }}
        docker push daelinc/minecraft-papermc:latest
